"""Project database schema compatibility shared by milestone stores."""

M0_SCHEMA_VERSION = 2
M1_SCHEMA_VERSION = 3
M2_SCHEMA_VERSION = 4
LATEST_SCHEMA_VERSION = M2_SCHEMA_VERSION

SUPPORTED_SCHEMA_VERSIONS = (
    M0_SCHEMA_VERSION,
    M1_SCHEMA_VERSION,
    M2_SCHEMA_VERSION,
)
